version: '3.3'
services:
  postgres:
    env_file:
      - ./.env
    image: "postgres:${POSTGRES_VERSION}"
    restart: always
    environment:
      - POSTGRES_DB=pizzaPolaka
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '2137:5432'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --username=${POSTGRES_USER} --dbname=pizzaPolaka"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  av:
    image: clamav/clamav
    container_name: clamav
    restart: unless-stopped
    volumes:
      - clam:/var/lib/clamav
    ports:
      - '3310:3310'
  migration:
    image: pepperpizza/api:1.0
    command: "npm run migrate"
    links:
      - postgres:postgres
    depends_on:
      postgres:
        condition: service_healthy
  api:
    env_file:
      - ./.env
    image: pepperpizza/api:1.0
    command: "npm start"
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
      - migration
volumes:
  postgres: null
  clam:
networks:
  outpost_network:
    external: true